name: etl-cicd-test

services:
  db_test:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-etl_test}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-etl_test}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-etl_test_password}
    volumes:
      - postgres-db-test-volume:/var/lib/postgresql/data
      - ./entrypoints/db/:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_LOCAL_TEST_PORT:-5433}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_TEST_USER:-etl_test} -d ${POSTGRES_TEST_DB:-etl_test}",
        ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres-db-test-volume:
